logging:
    level:
        'jhkim105.tutorials': trace
spring:
    datasource:
        hikari:
            maximum-pool-size: 10
        password: 111111
        url: jdbc:mariadb://localhost/demo_jpa_kotlin?createDatabaseIfNotExist=true
        username: root
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                id:
                    new_generator_mappings: false
    sql:
        init:
            mode: always
